-- GuardScan Database Schema
-- Migration: 001_initial_schema
-- Description: Initial database setup with clients, transactions, and telemetry tables
-- Created: 2025-11-14

-- ============================================================================
-- CLIENTS TABLE
-- ============================================================================
-- Stores client information and usage tracking
CREATE TABLE IF NOT EXISTS clients (
  client_id VARCHAR(255) PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total_loc_used BIGINT NOT NULL DEFAULT 0,
  plan_tier VARCHAR(50) NOT NULL DEFAULT 'free',
  email VARCHAR(255),
  last_seen_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}'::jsonb,

  -- Constraints
  CONSTRAINT valid_plan_tier CHECK (plan_tier IN ('free', 'starter', 'pro', 'enterprise')),
  CONSTRAINT non_negative_loc CHECK (total_loc_used >= 0)
);

-- Add comment for documentation
COMMENT ON TABLE clients IS 'Stores client information and usage tracking for GuardScan users';
COMMENT ON COLUMN clients.client_id IS 'Unique client identifier (UUID generated by CLI)';
COMMENT ON COLUMN clients.total_loc_used IS 'Total lines of code scanned across all scans';
COMMENT ON COLUMN clients.plan_tier IS 'Subscription tier: free, starter, pro, enterprise';
COMMENT ON COLUMN clients.metadata IS 'Additional client metadata (extensible JSON)';

-- ============================================================================
-- TRANSACTIONS TABLE
-- ============================================================================
-- Stores payment transactions and credit purchases
CREATE TABLE IF NOT EXISTS transactions (
  transaction_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id VARCHAR(255) NOT NULL REFERENCES clients(client_id) ON DELETE CASCADE,
  loc_purchased BIGINT NOT NULL,
  amount_usd DECIMAL(10, 2) NOT NULL,
  payment_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  stripe_payment_id VARCHAR(255),
  stripe_session_id VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb,

  -- Constraints
  CONSTRAINT valid_payment_status CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  CONSTRAINT positive_loc CHECK (loc_purchased > 0),
  CONSTRAINT positive_amount CHECK (amount_usd > 0)
);

-- Add comment for documentation
COMMENT ON TABLE transactions IS 'Stores payment transactions and LOC credit purchases';
COMMENT ON COLUMN transactions.loc_purchased IS 'Number of LOC credits purchased in this transaction';
COMMENT ON COLUMN transactions.amount_usd IS 'Amount paid in USD';
COMMENT ON COLUMN transactions.stripe_payment_id IS 'Stripe Payment Intent ID';
COMMENT ON COLUMN transactions.stripe_session_id IS 'Stripe Checkout Session ID';

-- ============================================================================
-- TELEMETRY TABLE
-- ============================================================================
-- Stores anonymized usage telemetry (privacy-preserving)
CREATE TABLE IF NOT EXISTS telemetry (
  event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id VARCHAR(255) NOT NULL,
  repo_id VARCHAR(255) NOT NULL,
  action_type VARCHAR(100) NOT NULL,
  duration_ms INTEGER,
  model VARCHAR(100),
  loc INTEGER,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb,

  -- Constraints
  CONSTRAINT valid_action_type CHECK (action_type IN (
    'init', 'run', 'security', 'test', 'sbom', 'perf',
    'mutation', 'rules', 'config', 'status', 'reset'
  )),
  CONSTRAINT positive_duration CHECK (duration_ms >= 0),
  CONSTRAINT positive_loc CHECK (loc >= 0)
);

-- Add comment for documentation
COMMENT ON TABLE telemetry IS 'Anonymized usage telemetry (no source code stored)';
COMMENT ON COLUMN telemetry.repo_id IS 'Hashed repository identifier (anonymized)';
COMMENT ON COLUMN telemetry.action_type IS 'CLI command executed';
COMMENT ON COLUMN telemetry.duration_ms IS 'Command execution duration in milliseconds';
COMMENT ON COLUMN telemetry.model IS 'AI model used (if applicable)';
COMMENT ON COLUMN telemetry.loc IS 'Lines of code processed in this action';

-- ============================================================================
-- CREDITS VIEW
-- ============================================================================
-- Materialized view for efficient credit balance queries
CREATE MATERIALIZED VIEW IF NOT EXISTS credits_balance AS
SELECT
  c.client_id,
  c.plan_tier,
  COALESCE(SUM(t.loc_purchased), 0) AS total_purchased,
  c.total_loc_used,
  COALESCE(SUM(t.loc_purchased), 0) - c.total_loc_used AS remaining_credits,
  MAX(t.created_at) AS last_purchase_date
FROM clients c
LEFT JOIN transactions t ON c.client_id = t.client_id AND t.payment_status = 'paid'
GROUP BY c.client_id, c.plan_tier, c.total_loc_used;

-- Add index for the materialized view
CREATE UNIQUE INDEX IF NOT EXISTS idx_credits_balance_client_id
ON credits_balance(client_id);

COMMENT ON MATERIALIZED VIEW credits_balance IS 'Efficient view for querying client credit balances';

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Clients table indexes
CREATE INDEX IF NOT EXISTS idx_clients_plan_tier ON clients(plan_tier);
CREATE INDEX IF NOT EXISTS idx_clients_created_at ON clients(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clients_email ON clients(email) WHERE email IS NOT NULL;

-- Transactions table indexes
CREATE INDEX IF NOT EXISTS idx_transactions_client_id ON transactions(client_id);
CREATE INDEX IF NOT EXISTS idx_transactions_payment_status ON transactions(payment_status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_stripe_payment_id ON transactions(stripe_payment_id) WHERE stripe_payment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_transactions_stripe_session_id ON transactions(stripe_session_id) WHERE stripe_session_id IS NOT NULL;

-- Composite index for common query pattern
CREATE INDEX IF NOT EXISTS idx_transactions_client_status
ON transactions(client_id, payment_status, created_at DESC);

-- Telemetry table indexes
CREATE INDEX IF NOT EXISTS idx_telemetry_client_id ON telemetry(client_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_repo_id ON telemetry(repo_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_action_type ON telemetry(action_type);
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp ON telemetry(timestamp DESC);

-- Composite index for analytics queries
CREATE INDEX IF NOT EXISTS idx_telemetry_client_action_time
ON telemetry(client_id, action_type, timestamp DESC);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for transactions table
CREATE TRIGGER update_transactions_updated_at
BEFORE UPDATE ON transactions
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Function to refresh credits_balance materialized view
CREATE OR REPLACE FUNCTION refresh_credits_balance()
RETURNS TRIGGER AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY credits_balance;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Triggers to refresh credits view
CREATE TRIGGER refresh_credits_on_transaction_change
AFTER INSERT OR UPDATE OR DELETE ON transactions
FOR EACH STATEMENT
EXECUTE FUNCTION refresh_credits_balance();

CREATE TRIGGER refresh_credits_on_client_change
AFTER UPDATE OF total_loc_used ON clients
FOR EACH STATEMENT
EXECUTE FUNCTION refresh_credits_balance();

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Free tier limits (can be configured)
INSERT INTO clients (client_id, plan_tier, total_loc_used, metadata)
VALUES ('system', 'enterprise', 0, '{"is_system": true, "description": "System account for internal operations"}')
ON CONFLICT (client_id) DO NOTHING;

-- Refresh the materialized view
REFRESH MATERIALIZED VIEW credits_balance;
